// The declarative env registry — every name of 06 §2.5 (44) + HANDOFF §5.4 (7) = 51, grouped as 06 §2.5 groups them,
// each with its scope, kind, purpose and D / P / Pr marks. `build-env-schema.ts` turns it into the one zod schema
// (01 §3.3); `scripts/env/generate-example.mts` renders `.env.example` from it (06 §2.5 — CI fails on drift).
// Split in two tables: `PUBLIC_ENV_ENTRIES` (lib/public-env-schema.ts — what a client bundle may see) and the server
// entries here; `ENV_SCHEMA.entries` composes both for the server reader and the generator. Never import this file
// from a client-importable module. Self-contained on purpose (type-only imports): the generator runs it under Node.
// Booleans are the literal "true" (absent = unset → the flag's code default; anything else = false), so their
// marks are informational. `NODE_ENV` absent = development (Node convention).
import type { EnvEntry, EnvGroup } from "../types";
import { PUBLIC_ENV_ENTRIES } from "./public-env-schema.ts"; // explicit extension: this file also runs un-bundled under Node (the generator)

const SERVER_ENV_ENTRIES = {
  // App
  VERCEL_ENV: {
    group: "App",
    scope: "server",
    kind: "enum",
    values: ["development", "preview", "production"],
    purpose:
      "set by Vercel: development | preview | production — selects the 06 §2.5 column",
    dev: "○",
    preview: "●",
    prod: "●",
  },
  CRON_SECRET: {
    group: "App",
    scope: "server",
    kind: "string",
    purpose:
      "Bearer for /api/cron/* (fail closed) — regenerated, never Sydney's",
    dev: "●",
    preview: "●",
    prod: "●",
    secret: true,
  },
  ADMIN_API_TOKEN: {
    group: "App",
    scope: "server",
    kind: "string",
    purpose: "Bearer for the Recruitment Agent route (04.10) — regenerated",
    dev: "●",
    preview: "●",
    prod: "●",
    secret: true,
  },
  SYSTEM_PARENT_ID: {
    group: "App",
    scope: "server",
    kind: "uuid",
    purpose:
      "uuid of the London system account (02 §4.1; created by migration 0002)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  ADMIN_EMAIL: {
    group: "App",
    scope: "server",
    kind: "email",
    purpose: "admin mailbox (config/senders.ts `admin`)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  SUPPORT_INBOX: {
    group: "App",
    scope: "server",
    kind: "email",
    purpose: "support mailbox (config/senders.ts `support`)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  // Supabase
  SUPABASE_SERVICE_ROLE_KEY: {
    group: "Supabase",
    scope: "server",
    kind: "string",
    purpose:
      "service-role key — server scope only; named uses in module READMEs (07 §5.1 rule 5)",
    dev: "●",
    preview: "●",
    prod: "●",
    secret: true,
  },
  // Stripe
  STRIPE_MODE: {
    group: "Stripe",
    scope: "server",
    kind: "enum",
    values: ["test", "live"],
    purpose:
      "test | live — key prefixes are asserted against it at boot (06 §2.2)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  STRIPE_SECRET_KEY: {
    group: "Stripe",
    scope: "server",
    kind: "string",
    purpose:
      "restricted key with only the purchase-paths permissions (07 §7.5)",
    dev: "●",
    preview: "●",
    prod: "●",
    secret: true,
  },
  STRIPE_WEBHOOK_SECRET: {
    group: "Stripe",
    scope: "server",
    kind: "string",
    purpose: "signing secret for /api/webhooks/stripe (fail closed)",
    dev: "●",
    preview: "●",
    prod: "●",
    secret: true,
  },
  STRIPE_PRICE_SELF_SERVE_APP_UPFRONT: {
    group: "Stripe",
    scope: "server",
    kind: "string",
    purpose:
      "price id — self-serve app, upfront to age 3 (03 §5.2; never a literal)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  STRIPE_PRICE_SELF_SERVE_APP_MONTHLY: {
    group: "Stripe",
    scope: "server",
    kind: "string",
    purpose: "price id — self-serve app, monthly (03 §5.2; never a literal)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  // Providers (01 §1.2 bindings)
  PURCHASE_PROVIDER: {
    group: "Providers",
    scope: "server",
    kind: "enum",
    values: ["stripe-uk", "stub-stripe"],
    purpose:
      "stripe-uk | stub-stripe — the stub is refused in production (07 §5.5)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  STUB_EVENT_SECRET: {
    group: "Providers",
    scope: "server",
    kind: "string",
    purpose:
      "signs stub provider events; required iff stub-stripe, never in production (07 §5.5)",
    dev: "○",
    preview: "○",
    prod: "—",
    secret: true,
  },
  EMAIL_PROVIDER: {
    group: "Providers",
    scope: "server",
    kind: "enum",
    values: ["resend", "stub-email"],
    purpose: "resend | stub-email (03 §8.1)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  SMS_PROVIDER: {
    group: "Providers",
    scope: "server",
    kind: "enum",
    values: ["null-sms"],
    purpose: "null-sms — the only value; no SMS day one (N-11, ADR-063)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  AREAS_SOURCE: {
    group: "Providers",
    scope: "server",
    kind: "enum",
    values: ["db", "stub"],
    purpose: "db | stub — the areas connector binding (03 §6.3)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  // Email
  RESEND_API_KEY: {
    group: "Email",
    scope: "server",
    kind: "string",
    purpose:
      "Resend key scoped to the London domain; dev may omit under dry-run",
    dev: "○",
    preview: "●",
    prod: "●",
    secret: true,
  },
  EMAIL_DEV_DRY_RUN: {
    group: "Email",
    scope: "server",
    kind: "boolean",
    purpose: "dev only: email_logs rows as dry_run, nothing sent (08.03)",
    dev: "●",
    preview: "—",
    prod: "—",
    devOnly: true,
  },
  // AI
  OPENAI_API_KEY: {
    group: "AI",
    scope: "server",
    kind: "string",
    purpose: "project-scoped key, zero retention (07 §7.5)",
    dev: "○",
    preview: "●",
    prod: "●",
    secret: true,
  },
  GOOGLE_AI_API_KEY: {
    group: "AI",
    scope: "server",
    kind: "string",
    purpose: "Gemini key for Katie",
    dev: "○",
    preview: "●",
    prod: "●",
    secret: true,
  },
  KATIE_DAILY_LIMIT_USD: {
    group: "AI",
    scope: "server",
    kind: "number",
    purpose:
      "daily Katie cost cap in USD (Gemini bills USD — 01 §1.2); read by config/katie.ts",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  // Analytics (ADR-055; consent-gated consumer)
  META_CAPI_ACCESS_TOKEN: {
    group: "Analytics",
    scope: "server",
    kind: "string",
    purpose: "Conversions API token for the London dataset",
    dev: "—",
    preview: "—",
    prod: "●",
    secret: true,
  },
  META_DATASET_ID: {
    group: "Analytics",
    scope: "server",
    kind: "string",
    purpose: "London dataset id (≠ Sydney's — 08 §8 item 3)",
    dev: "—",
    preview: "—",
    prod: "●",
  },
  // Flags (01 §3.4; read through FLAGS.x only; booleans = the literal "true", absent = the code default)
  KATIE_ENABLED: {
    group: "Flags",
    scope: "server",
    kind: "boolean",
    purpose: "flag KATIE (server) — on everywhere; the app is the product",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  INVITE_LINKS_ENABLED: {
    group: "Flags",
    scope: "server",
    kind: "boolean",
    purpose: "flag INVITE_LINKS — on (stage table row 8; ADR-031)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  NEW_TRIALS_ENABLED: {
    group: "Flags",
    scope: "server",
    kind: "boolean",
    purpose: "flag NEW_TRIALS — on (ADR-025 / 059)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  PAYMENTS_ENABLED: {
    group: "Flags",
    scope: "server",
    kind: "boolean",
    purpose: "flag PAYMENTS — on; kill switch only (06.11)",
    dev: "●",
    preview: "●",
    prod: "●",
  },
  BONUS_PROGRAM_ENABLED: {
    group: "Flags",
    scope: "server",
    kind: "boolean",
    purpose:
      "flag BONUS_PROGRAM (server) — off in every environment (ADR-022 / 053 / 060)",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  PROACTIVE_ENABLED: {
    group: "Flags",
    scope: "server",
    kind: "boolean",
    purpose: "flag PROACTIVE (Katie) — value per 01 §10 O-5",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  // Flags (Katie) — carried as Sydney ships them (07.08); values set by SPECS/05-katie-and-app/
  KATIE_STREAM_DIAGNOSTICS: {
    group: "Flags (Katie)",
    scope: "server",
    kind: "boolean",
    purpose: "Katie sub-flag (07.08)",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  KATIE_PRELOAD_PASSTHROUGH_ENABLED: {
    group: "Flags (Katie)",
    scope: "server",
    kind: "boolean",
    purpose: "Katie sub-flag (07.08)",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  KATIE_PARALLEL_TOOLS_ENABLED: {
    group: "Flags (Katie)",
    scope: "server",
    kind: "boolean",
    purpose: "Katie sub-flag (07.08)",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  KATIE_IMAGE_MARKER_ENABLED: {
    group: "Flags (Katie)",
    scope: "server",
    kind: "boolean",
    purpose: "Katie sub-flag (07.08)",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  KATIE_ALWAYS_ON_CONTEXT_ENABLED: {
    group: "Flags (Katie)",
    scope: "server",
    kind: "boolean",
    purpose: "Katie sub-flag (07.08)",
    dev: "○",
    preview: "○",
    prod: "○",
  },
  // Monitoring (06 §7; ADR-106)
  SENTRY_DSN: {
    group: "Monitoring",
    scope: "server",
    kind: "url",
    purpose: "Sentry DSN, server (ADR-106)",
    dev: "—",
    preview: "●",
    prod: "●",
  },
  ALERT_WEBHOOK_URL: {
    group: "Monitoring",
    scope: "server",
    kind: "url",
    purpose: "Slack alert-channel webhook (06 §7.2; ADR-106)",
    dev: "—",
    preview: "●",
    prod: "●",
    secret: true,
  },
} as const satisfies Readonly<Record<string, EnvEntry>>;

export const ENV_SCHEMA = Object.freeze({
  groups: [
    "App",
    "Supabase",
    "Stripe",
    "Providers",
    "Email",
    "AI",
    "Analytics",
    "Flags",
    "Flags (dev)",
    "Flags (Katie)",
    "Monitoring",
  ] as const satisfies ReadonlyArray<EnvGroup>,
  entries: { ...PUBLIC_ENV_ENTRIES, ...SERVER_ENV_ENTRIES },
});
