// 02 §3 — cluster "marketplace". Values verbatim, add-only; tuple index = ordinal (02 C-1).
// connection_stage: the spine first (03 §2.2, glossary §1.2), then the branch stages — so "≥ INTRO_SCHEDULED"
// reads work along the spine; branch stages sit after ACTIVE and are never compared by ordinal.
export const MARKETPLACE_ENUMS = Object.freeze({
  position_stage: Object.freeze([
    "DRAFT",
    "OPEN",
    "CONNECTING",
    "ACTIVE",
    "ENDED",
    "CLOSED",
  ] as const),
  connection_stage: Object.freeze([
    "REQUEST_SENT",
    "ACCEPTED",
    "INTRO_SCHEDULED",
    "INTRO_COMPLETE",
    "TRIAL_ARRANGED",
    "TRIAL_COMPLETE",
    "OFFERED",
    "CONFIRMED",
    "ACTIVE",
    "NANNY_APPLIED",
    "REQUEST_EXPIRED",
    "DECLINED",
    "REQUEST_CANCELLED",
    "SCHEDULE_EXPIRED",
    "INTRO_INCOMPLETE",
    "AWAITING_RESPONSE",
    "NOT_HIRED",
    "NOT_SELECTED",
    "FINISHED",
    "CANCELLED_BY_PARENT",
    "CANCELLED_BY_NANNY",
  ] as const),
  placement_state: Object.freeze(["CONFIRMED", "ACTIVE", "ENDED"] as const),
  call_state: Object.freeze(["awaiting-slot", "slot-chosen", "done"] as const), // ADR-073
  call_type: Object.freeze([
    "matchmaking",
    "onboarding",
    "nanny-commission",
  ] as const),
  call_outcome: Object.freeze([
    "proceeding",
    "not-now",
    "not-proceeding",
    "no-answer",
    "cancelled",
  ] as const),
  end_reason: Object.freeze([
    "natural",
    "nanny_left",
    "no_longer_needed",
    "mutual",
    "child_aged_out",
    "relocation",
    "other",
  ] as const),
  close_reason: Object.freeze([
    "parent_closed",
    "no_candidates",
    "admin_closed",
  ] as const),
  position_source: Object.freeze([
    "results_signup",
    "in_app",
    "admin",
    "invite",
    "agent",
  ] as const),
  signup_source: Object.freeze(["results", "cold", "invite", "admin"] as const),
  precheck_status: Object.freeze([
    "notified",
    "pending_wave",
    "viewed",
    "interested",
    "declined",
    "expired",
  ] as const),
  connection_origin: Object.freeze([
    "parent_request",
    "precheck_response",
    "nanny_application",
    "admin",
  ] as const),
  meeting_outcome: Object.freeze([
    "hired",
    "not_hired",
    "awaiting",
    "trial",
    "incomplete",
  ] as const),
  schedule_type: Object.freeze(["fixed", "flexible"] as const),
  placement_source: Object.freeze(["connection", "invite_shell"] as const),
});
