// The copy claim as an executable test (ADR-120 rule 1; ADR-124). This surface is where the ban bites hardest:
// it is the only place in the parent journey that names an amount, and three of the banned words — *price*,
// *fee*, *free* — are the obvious ones to reach for here. Two things are checked, and the first is the stronger:
//
//   1. **Every string a parent actually reads**, generated by running `moneyPageView` over all nine standings.
//      That is the rendered test in miniature: it reads the words themselves rather than the file they live in,
//      so a reword cannot pass by moving a sentence.
//   2. The rendered `components/` and the three owned route files, file-scanned like `1e`'s suite.
//
// **Scope, and why the route files need one narrowing.** 04 §6.2 fixes the routes at `/parent/subscribe` and
// `/parent/subscription`, and *subscription* is on the 05 §5.2 list. A URL path is an address, not a word a
// parent reads — the screens themselves say "your bundle" and never "subscription" — so path literals are
// stripped before matching, and nothing else is. `lib/` and `types.ts` are out of scope for the same reason
// `1e` put them out of scope: they carry the contract's own vocabulary (`instalments` is 03 §5.2's `PlanShape`
// kind and a 02 §3 enum value; `parent_subscriptions` is a table). The static check scans them and reports them
// under the accepted `banned-literals` red.
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { LOCALE, PRICES } from "@/modules/config";
import type { AccessState } from "../types";
import { moneyPageView } from "../lib/money-page-view";

const REPO_ROOT = resolve(__dirname, "../../../..");
const COMPONENTS_DIR = resolve(__dirname, "../components");
const WORD_LIST = resolve(REPO_ROOT, "scripts/ci/banned-words.txt");

const OWNED_ROUTE_FILES = [
  "src/app/parent/bundle/page.tsx",
  "src/app/parent/subscribe/page.tsx",
  "src/app/parent/subscription/page.tsx",
];

const AT = "2026-03-01T09:00:00.000Z";
const LATER = "2026-04-01T09:00:00.000Z";
const money = (pence: number) => ({ pence, currency: LOCALE.currency }) as const;

/** One of every standing in 03 §5.2, so no branch of the view escapes the word list. */
const EVERY_STANDING: ReadonlyArray<AccessState> = [
  { state: "none" },
  { state: "deposit-paid", depositPaidAt: AT, pence: PRICES.depositPence },
  {
    state: "placed",
    accessUntil: LATER,
    startedAt: AT,
    paymentDueAt: LATER,
    balance: money(75_000),
    firstWeekWages: money(60_000),
    satisfactionWindowEndsAt: LATER,
  },
  { state: "trial", accessUntil: LATER, trialEndsAt: LATER },
  {
    state: "active",
    accessUntil: LATER,
    shape: { kind: "instalments", count: PRICES.bundleMonthlyCount },
    paidCount: 1,
    remaining: 11,
    nextPaymentAt: LATER,
    standing: "good",
  },
  {
    state: "active",
    accessUntil: LATER,
    shape: { kind: "instalments", count: PRICES.bundleMonthlyCount },
    paidCount: 1,
    remaining: 11,
    nextPaymentAt: LATER,
    standing: "past-due",
    graceUntil: LATER,
  },
  {
    state: "active",
    accessUntil: LATER,
    shape: { kind: "upfront" },
    paidCount: 1,
    remaining: 0,
    nextPaymentAt: null,
    standing: "good",
    cancelledAt: AT,
  },
  {
    state: "paid-in-full",
    accessUntil: LATER,
    shape: { kind: "upfront" },
    paidAt: AT,
  },
  {
    state: "toggled",
    on: true,
    accessUntil: LATER,
    reason: "goodwill",
    toggledBy: "admin-1" as never,
    at: AT,
  },
  {
    state: "toggled",
    on: false,
    accessUntil: LATER,
    reason: "unpaid",
    toggledBy: "admin-1" as never,
    at: AT,
  },
  { state: "lapsed", lapsedAt: AT, reason: "trial-ended" },
  { state: "lapsed", lapsedAt: AT, reason: "past-due" },
  { state: "lapsed", lapsedAt: AT, reason: "cancelled" },
  { state: "lapsed", lapsedAt: AT, reason: "access-ended" },
].map((state) => ({
  ...(state as AccessState),
  deposit: { paidAt: AT, pence: PRICES.depositPence },
}));

function listFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory())
      return entry === "__tests__" ? [] : listFiles(full);
    return /\.(ts|tsx|md)$/.test(entry) ? [full] : [];
  });
}

const phrases = readFileSync(WORD_LIST, "utf8")
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line !== "" && !line.startsWith("#"));

const pattern = new RegExp(
  `\\b(?:${phrases
    .map((phrase) =>
      phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "[ -]"),
    )
    .join("|")})\\b`,
  "gi",
);

/**
 * Three things are stripped before the file scan, each because it is a **name the contract fixes**, not a word a
 * parent reads. Nothing else is stripped, and the strings a parent actually reads (the cases above) get no
 * exclusion at all.
 *
 *   `/parent/subscribe` · `/parent/subscription` — 04 §6.2 fixes the routes; a URL path is an address, and the
 *      screens themselves say "your bundle".
 *   `Price` · `prices()` — 03 §5.2's type and method on the connector; renaming them is a contract change.
 *   `"instalments"` — 03 §5.2's `PlanShape` kind and a 02 §3 enum value; renaming it is a migration.
 *
 * `1e`'s suite made the same call for `lib/` and `types.ts`; this one keeps `components/` and the route files
 * in scope and narrows to the three names instead, which is the tighter of the two.
 */
const CONTRACT_NAMES =
  /\/parent\/subscriptions?|\bPrice\b|\bprices\b|"instalments"|'instalments'/gu;

const withoutPaths = (text: string): string => text.replace(CONTRACT_NAMES, "_");

const hitsIn = (file: string): string[] =>
  withoutPaths(readFileSync(file, "utf8"))
    .split("\n")
    .flatMap((line, index) => {
      const matches = line.match(pattern);
      return matches
        ? [`${relative(REPO_ROOT, file)}:${index + 1}: ${matches.join(", ")}`]
        : [];
    });

const wordsOf = (state: AccessState): string => {
  const view = moneyPageView(state);
  return [
    view.headline,
    view.body,
    ...view.facts.flatMap((fact) => [fact.label, fact.value]),
  ].join(" \n ");
};

describe("payments — the words a parent reads (00-glossary §6 / §8; 05 §5.2)", () => {
  it("loads the 05 §5.2 list", () => {
    expect(phrases).toContain("free");
    expect(phrases).toContain("price");
    expect(phrases).toContain("fee");
    expect(phrases.length).toBeGreaterThan(40);
  });

  it.each(EVERY_STANDING.map((state) => [state.state, state] as const))(
    "the %s standing renders no banned word",
    (_name, state) => {
      expect(wordsOf(state).match(pattern) ?? []).toEqual([]);
    },
  );

  it("never shows the self-serve road as free (ADR-082)", () => {
    for (const state of EVERY_STANDING)
      expect(wordsOf(state).toLowerCase()).not.toMatch(/\bfree\b/u);
  });

  it("never promises lifetime or forever, and says the third birthday instead (ADR-083 / 084)", () => {
    const open = wordsOf({ state: "trial", accessUntil: null, trialEndsAt: AT });
    expect(open).not.toMatch(/lifetime|forever|unlimited/iu);
    expect(open).toContain(`turns ${PRICES.accessAgeYears}`);
    expect(open).toContain("every child you have");
  });

  it("tells a placed family the promise in the offer's own words (ADR-094)", () => {
    const placed = moneyPageView(EVERY_STANDING[2] as AccessState);
    expect(placed.body).toContain("What's left to pay");
    expect(placed.facts.map((f) => f.label)).toContain("Left to pay");
    // The deposit and the first week are named as already taken off — the whole promise of the money model.
    expect(placed.body).toContain("already taken off");
  });

  it("never tells a deposit-paid family the app is open (ADR-097)", () => {
    const view = moneyPageView({
      state: "deposit-paid",
      depositPaidAt: AT,
      pence: PRICES.depositPence,
    });
    expect(view.open).toBe(false);
    expect(view.body).toContain("switches on the day your nanny starts");
  });

  it.each(listFiles(COMPONENTS_DIR).map((file) => relative(REPO_ROOT, file)))(
    "%s carries no banned word",
    (file) => {
      expect(hitsIn(resolve(REPO_ROOT, file))).toEqual([]);
    },
  );

  it.each(OWNED_ROUTE_FILES)(
    "%s (owned route file) carries no banned word",
    (file) => {
      expect(hitsIn(resolve(REPO_ROOT, file))).toEqual([]);
    },
  );
});
