// auth — the module's type surface (01 §2.5). Copied from `03-interface-contracts.md` §1.4 with the names that
// contract spells, plus the driver seam the inside is built on. Values live in index.ts. **Types only**, so a client
// component may `import type` from the connector without dragging the Supabase SDK into its bundle.
import type { NextRequest, NextResponse } from "next/server";
import type { ClientResult, UnitOfWorkJoin } from "@/modules/platform";
import type { BucketKey } from "@/modules/config";
import type {
  Actor,
  Database,
  DatabaseShape,
  Email,
  EnumValue,
  Instant,
  ModuleName,
  Query,
  Result,
  UnitOfWork,
  Url,
  UserId,
} from "@/modules/shared-types";

// ── Session + roles (03 §1.4; 01 §4d) ──

/** `parent` · `nanny` · `admin` — "any admin login", no `super_admin` (ADR-030; 02 §3 `user_role`, §5 row 7). */
export type Role = EnumValue<"user_role">;

/**
 * The two customer roles. `shared-types/actor.ts` declares the same type but the barrel does not re-export it
 * (the S2 gap `platform` hit for `ConsentParty`), so it is derived here from the same enum rather than widened.
 */
export type CustomerRole = Exclude<Role, "admin">;

/** 03 §1.4 verbatim. `mfaVerified` = Supabase `aal2`, required for `admin` (07 §5.4 row 2). */
export type Session = {
  readonly userId: UserId;
  readonly role: Role;
  readonly mfaVerified: boolean;
  readonly expiresAt: Instant;
};

/**
 * What the middleware gets back from `refreshSession`: a `Session` plus the one extra signal the gate needs and
 * cannot get a second time (01 §4d step 3 — the edge runtime has no `next/headers`, so the gate reads the
 * password signal in the same round-trip that rotates the cookies). A `GateSession` **is** a `Session`, so the
 * 03 §1.4 return type is honoured and no caller that knows only `Session` changes.
 */
export type GateSession = Session & {
  readonly needsPasswordSetup: boolean;
};

/**
 * Self-signup produces a customer role only: no path a visitor can reach may write `admin`
 * (07 §5.4 row 3 — admin accounts are created by migration / service role; `grantRole` is the admin-actor road).
 */
export type SignUpInput = {
  readonly email: Email;
  readonly password: string;
  readonly role: CustomerRole;
  /** Where Supabase sends the confirmation link back to (`handleAuthCallback`, ADR-042). */
  readonly emailRedirectTo?: Url;
};

export type SignInInput = {
  readonly email: Email;
  readonly password: string;
};

// ── Errors (03 §1.4: `UNAUTHENTICATED` · `FORBIDDEN { reason }` · `INTERNAL`) ──

/** `role` = wrong role · `mfa` = admin without `aal2` (07 §5.4 row 2) · `scope` = a service-scope refusal. */
export type AuthFailureReason = "role" | "mfa" | "scope";

export type AuthErrorDetails = {
  readonly reason: AuthFailureReason;
};

// ── Data-access port (01 §6.3 amended; 03 §1.4) ──

/**
 * The generated `Database["public"]` shape (01 §6.2), landed by S5 with the `0000`–`0016` migration set.
 * `Database` is regenerated by `npm run types:generate` and diffed by CI's `types-drift`, so this type moves
 * only when the schema does. `Query` deliberately has no default for `DB`, so every call site names its shape
 * and this swap surfaced each one.
 */
export type AppDatabase = Database["public"];

/** `session` = RLS as the caller; `service` = named jobs and definers only, logged (03 §1.4). */
export type DataScope = "session" | "service";

/** A module's own repo function over `auth`'s narrow `Query` surface — not a client (03 §1.4). */
export type NamedOperation<T, DB extends DatabaseShape = AppDatabase> = {
  readonly name: `${ModuleName}.${string}`;
  readonly exec: (q: Query<DB>) => Promise<T>;
};

export type RunOptions = {
  readonly uow?: UnitOfWork;
  readonly scope?: DataScope;
};

/** A storage object by bucket + path — never a URL, never a bucket path built outside its owning module (01 §6.3). */
export type StorageRef = {
  readonly bucket: BucketKey;
  readonly path: string;
};

export interface DataAccessPort<DB extends DatabaseShape = AppDatabase> {
  run<T>(op: NamedOperation<T, DB>, opts?: RunOptions): Promise<Result<T>>;
  /** The one signed-URL minter (07 §5.3 rule 1); TTLs come from `SECURITY.signedUrlTtlSeconds`. */
  signUrl(ref: StorageRef, ttlSeconds: number): Promise<Result<Url>>;
}

// ── The connector (03 §1.4) ──

export interface Auth<DB extends DatabaseShape = AppDatabase> {
  /** From the request; `null` for anonymous, never throws (03 §1.4). */
  getSession(): Promise<Result<Session | null>>;
  requireRole(
    role: Role | ReadonlyArray<Role>,
  ): Promise<Result<Session, AuthErrorDetails>>;
  getCurrentUserId(): Promise<Result<UserId | null>>;
  readonly data: DataAccessPort<DB>;
  /** Middleware only (01 §4d step 1): the one place session cookies are rotated. */
  refreshSession(
    req: NextRequest,
    res: NextResponse,
  ): Promise<Result<GateSession | null>>;
  /**
   * 01 §4d step 3 — a signed-in user with no password (ADR-042) is routed to set-password, never shown an error.
   * **Connector extension:** 03 §1.4 does not name this method; the gate rule it serves is stated in 01 §4d and
   * has no other expressible signal. Raised for ratification in the L-005 S4 entry (amend-first).
   */
  needsPasswordSetup(): Promise<Result<boolean>>;
  signUp(input: SignUpInput): Promise<Result<Session>>;
  signIn(input: SignInInput): Promise<Result<Session>>;
  signOut(): Promise<Result<void>>;
  setPassword(newPassword: string): Promise<Result<void>>;
  /** ADR-042 passwordless catch: the caller sends the email; this exchanges the code (03 §1.4). */
  handleAuthCallback(code: string): Promise<Result<Session>>;
  /**
   * S-X-09's forgot half and the **anonymous** half of ADR-042's passwordless catch, in one method because under
   * ADR-132 they cannot be told apart from outside: it answers the **same `Result` for every address**, and the
   * only difference is what the account itself receives — a recovery link for an address the provider knows,
   * nothing for one it does not. A provider failure also answers `ok` (logged, never surfaced), because a caller
   * that could tell "sent" from "not sent" would be an account-enumeration oracle on a public form (07 §4).
   *
   * **Connector extension:** 03 §1.4 names `setPassword` and `handleAuthCallback` and says "the caller sends the
   * email", but no method sends it — the gap `1c` pinned (4). Raised for ratification, amend-first.
   */
  requestPasswordReset(email: Email): Promise<Result<void>>;
  /** Admin actor only, logged (03 §1.4; 07 §5.4 row 3). */
  grantRole(userId: UserId, role: Role, actor: Actor): Promise<Result<void>>;
  isParent(s: Session): boolean;
  isNanny(s: Session): boolean;
  isAdmin(s: Session): boolean;
}

// ── The driver seam (the inside only; never re-exported to a business module) ──

/** What the identity provider knows about the caller, reduced to the fields the gate needs. */
export type DriverUser = {
  readonly id: string;
  readonly email: string | null;
  /** `false` ⇒ ADR-042's passwordless account — the gate routes it to set-password (01 §4d step 3). */
  readonly hasPassword: boolean;
  /** Supabase assurance level; `aal2` is `mfaVerified` (07 §5.4 row 2). */
  readonly aal: string | null;
  /** Session expiry as an epoch-second stamp, as the provider reports it. */
  readonly expiresAtEpochSeconds: number | null;
};

/**
 * The narrow surface `createAuth` is written against: one implementation over `@supabase/ssr`
 * (`supabaseAuthDriver`), one in memory (`stub-auth`). No `@supabase/*` type crosses this seam, so the module is
 * unit-testable with no network and the stub honours the connector trivially (05 §3 rules 1–2).
 */
export interface AuthDriver<DB extends DatabaseShape = AppDatabase> {
  /** Reads the caller's identity from the ambient request context; `null` when anonymous. Never throws. */
  currentUser(): Promise<DriverUser | null>;
  /** Rotates the session cookies onto `res` and returns the refreshed identity (middleware only). */
  refresh(req: NextRequest, res: NextResponse): Promise<DriverUser | null>;
  /** `user_roles.role` for a user (02 §4.1); `null` when no row exists. */
  roleOf(userId: string): Promise<Role | null>;
  signInWithPassword(input: SignInInput): Promise<DriverUser>;
  signUpWithPassword(input: SignUpInput): Promise<DriverUser>;
  signOut(): Promise<void>;
  updatePassword(newPassword: string): Promise<void>;
  exchangeCodeForSession(code: string): Promise<DriverUser>;
  /**
   * Asks the identity provider to email a recovery link landing on `redirectTo`. The provider is the one that
   * knows whether the address exists and it never says (07 §4) — so this resolves either way and the connector
   * never learns which happened.
   */
  sendRecoveryEmail(email: string, redirectTo: string): Promise<void>;
  /** Writes the `user_roles` row from a server-side value (07 §10.1); service scope. */
  writeRole(userId: string, role: Role): Promise<void>;
  /** The narrow typed query surface for the given scope (03 §1.4). */
  query(scope: DataScope): Query<DB>;
  createSignedUrl(ref: StorageRef, ttlSeconds: number): Promise<string>;
}

/**
 * What `createAuth` needs beyond the driver. `unitOfWork` is the join the data port honours `{ uow }` through
 * (ADR-127 — one RPC is one transaction); absent, the port defaults to `platform`'s module-level join, which
 * follows whatever binding `configureUnitOfWork` installed and refuses every token until boot installs one.
 */
export type AuthDeps<DB extends DatabaseShape = AppDatabase> = {
  readonly driver: AuthDriver<DB>;
  readonly unitOfWork?: UnitOfWorkJoin;
};

// ── stub-auth (05 §3 rule 1: production code inside the module it stubs) ──

/** One link the stub's provider would have emailed (`StubAuthOptions.onRecoveryEmail`). */
export type RecoveryEmailSent = {
  readonly email: Email;
  readonly redirectTo: string;
};

/** One in-memory account. No `password` ⇒ ADR-042's passwordless account. */
export type StubUser = {
  readonly id: string;
  readonly email: Email;
  readonly password?: string;
  /** Absent ⇒ authenticated with the provider but not a known actor — the gate treats it as no session. */
  readonly role?: Role;
  readonly mfaVerified?: boolean;
};

export type StubAuthOptions = {
  readonly users?: ReadonlyArray<StubUser>;
  readonly signedInUserId?: string;
  /** Rows a `NamedOperation` sees; the stub's "test schema" behind the same port (03 §11 row 9). */
  readonly tables?: Readonly<Record<string, ReadonlyArray<unknown>>>;
  /** The unit-of-work join (`AuthDeps.unitOfWork`); the stub honours `{ uow }` exactly as the real inside does. */
  readonly unitOfWork?: UnitOfWorkJoin;
  /**
   * The stub's outbox. Called once for each recovery link the provider would actually send — for a seeded address
   * only, never for an unknown one, which is the whole behaviour a no-enumeration test has to be able to see.
   */
  readonly onRecoveryEmail?: (sent: RecoveryEmailSent) => void;
};

// ── The gate (01 §4d) and the one `(auth)` surface this unit owns ──

export type GateInput = {
  readonly pathname: string;
  readonly search?: string;
  readonly session: GateSession | null;
};

export type GateDecision =
  | { readonly kind: "allow" }
  | { readonly kind: "redirect"; readonly to: string };

/** The set-password action's shape, so the client component never imports the connector barrel. */
export type SetPasswordAction = (
  previous: unknown,
  formData: FormData,
) => Promise<ClientResult<void>>;

export type SetPasswordFormProps = {
  readonly action: SetPasswordAction;
  readonly minLength: number;
  readonly signInHref: string;
};
