// 03 §8.2 — every `TemplateId` the day-one registry names, as a value so a table test can walk them (03 §11
// row 7; 05 §3). One entry per key of `TemplateRegistry`; the `satisfies` keeps the two in step.
import type { TemplateId } from "../types";

export const TEMPLATE_IDS = Object.freeze([
  "welcome-parent",
  "welcome-parent-position",
  "welcome-parent-invited",
  "welcome-nanny",
  "call-confirmation",
  "call-rescheduled",
  "call-cancelled",
  "call-reminder",
  "admin-call-due",
  "admin-commission-booking",
  "precheck-nanny",
  "precheck-nanny-reminder",
  "precheck-parent-response",
  "precheck-complete",
  "connection-requested",
  "connection-accepted",
  "connection-declined",
  "connection-expired-parent",
  "connection-expired-nanny",
  "meeting-scheduled",
  "connection-followup-parent",
  "meeting-followup-nanny",
  "trial-followup-nanny",
  "confirm-nanny",
  "position-offered",
  "no-candidates-left",
  "placement-confirmed-parent",
  "placement-confirmed-nanny",
  "hire-confirmation-family",
  "hire-confirmation-nanny",
  "verification-pending",
  "verification-approved",
  "verification-action-needed",
  "verification-barred",
  "admin-nanny-barred",
  "verification-reminder",
  "bundle-payment-link",
  "app-ready",
  "trial-reminder",
  "feed-post",
  "contact-request",
  "contact-request-public",
  "support-reply",
  "admin-contact",
  "availability-updated",
  "admin-test",
] as const satisfies ReadonlyArray<TemplateId>);
