// The 26 day-one modules (00 §3; HANDOFF §4.1). No module exists that is not in this list.
export const MODULE_NAMES = Object.freeze([
  "config",
  "shared-types",
  "public-site",
  "areas",
  "matching",
  "scoring",
  "positions",
  "call-layer",
  "connections",
  "admin-on-behalf",
  "placements",
  "hire-docs",
  "auth",
  "onboarding-parent",
  "onboarding-nanny",
  "verification",
  "vetting-providers",
  "admin-verification",
  "comms",
  "payments",
  "purchase-paths",
  "scheduling",
  "platform",
  "access-gate",
  "app",
  "admin",
] as const);
